services:
  pythonapp:
    build: ./Python Application/
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mysql

  mysql:
    volumes: 
      - mysqldata:/var/lib/mysql
    build: ./Database/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
  tool:
    image: phpmyadmin
    ports: 
    - "8085:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    
volumes:
  mysqldata:
